# https://github.com/marketplace/actions/deploy-to-github-pages

name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    name: Build + Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      # https://github.com/actions/setup-node/#v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install
        run: yarn

      - name: Build
        run: yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
        # https://github.com/marketplace/actions/github-pages-action#%EF%B8%8F-first-deployment-with-github_token
          github_token: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages 
          FOLDER: build 
