# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Yarn CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    # https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-nodejs
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # https://github.com/actions/setup-node/#v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install
        run: yarn

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test